const products = [
    {
      id: 1,
      name: "Men's T-Shirt",
      image: "https://m.media-amazon.com/images/I/41ZM7fTZSWL._SX679_.jpg",
      category: "Men",
      description: "Comfortable cotton t-shirt for men.",
      price: 1200,
    },
    {
      id: 2,
      name: "Men's Jeans",
      image: "https://m.media-amazon.com/images/I/61lg3ufEX8L._SY879_.jpg",
      category: "Men",
      description: "Stylish denim jeans for men.",
      price: 2500,
    },
    {
      id: 3,
      name: "Men's Jacket",
      image: "https://m.media-amazon.com/images/I/61yp3ndG1JL._SY879_.jpg",
      category: "Men",
      description: "Warm and cozy jacket for men.",
      price: 3500,
    },
    {
      id: 4,
      name: "Men's Shoes",
      image: "https://m.media-amazon.com/images/I/71u78BeE5TL._SX695_.jpg",
      category: "Men",
      description: "Comfortable and stylish shoes for men.",
      price: 3000,
    },
    {
      id: 5,
      name: "Women's Dress",
      image: "https://m.media-amazon.com/images/I/61Cu27WVA9L._SX679_.jpg",
      category: "Women",
      description: "Elegant dress for women.",
      price: 4000,
    },
    {
      id: 6,
      name: "Women's Handbag",
      image: "https://m.media-amazon.com/images/I/61ljZ3YohfL._SY695_.jpg",
      category: "Women",
      description: "Stylish handbag for women.",
      price: 2500,
    },
    {
      id: 7,
      name: "Women's Shoes",
      image: "https://example.com/path/to/womens_shoes.jpg",
      category: "Women",
      description: "Comfortable and stylish shoes for women.",
      price: 3000,
    },
    {
      id: 8,
      name: "Women's Scarf",
      image: "https://m.media-amazon.com/images/I/411psMdH9zL._SY395_SX395_.jpg",
      category: "Women",
      description: "Beautiful scarf for women.",
      price: 1000,
    },
    {
      id: 9,
      name: "Kids' T-Shirt",
      image: "https://m.media-amazon.com/images/I/71FyyR00qhL._SY879_.jpg",
      category: "Kids",
      description: "Comfortable cotton t-shirt for kids.",
      price: 600,
    },
    {
      id: 10,
      name: "Kids' Jeans",
      image: "https://m.media-amazon.com/images/I/616LBK7CPoL._SX679_.jpg",
      category: "Kids",
      description: "Stylish denim jeans for kids.",
      price: 1500,
    },
    {
      id: 11,
      name: "Kids' Jacket",
      image: "https://m.media-amazon.com/images/I/31DvKIGSCJL._SX342_SY445_.jpg",
      category: "Kids",
      description: "Warm and cozy jacket for kids.",
      price: 2000,
    },
    {
      id: 12,
      name: "Kids' Shoes",
      image: "https://m.media-amazon.com/images/I/71RaDVFdw8L._SX695_.jpg",
      category: "Kids",
      description: "Comfortable and stylish shoes for kids.",
      price: 1800,
    },
    {
      id: 13,
      name: "Men's Hat",
      image: "https://m.media-amazon.com/images/I/51Iyb4GJNCL.jpg",
      category: "Men",
      description: "Stylish hat for men.",
      price: 800,
    },
    {
      id: 14,
      name: "Women's Hat",
      image: "https://m.media-amazon.com/images/I/41f4hxhH+OL.jpg",
      category: "Women",
      description: "Stylish hat for women.",
      price: 1000,
    },
    {
      id: 15,
      name: "Kids' Hat",
      image: "https://m.media-amazon.com/images/I/31NcI+abuQL.jpg",
      category: "Kids",
      description: "Stylish hat for kids.",
      price: 600,
    },
    {
      id: 16,
      name: "Men's Watch",
      image: "https://www.amazon.in/Titan-Karishma-Stainless-Watch-NL1639SM02-NN1639SM02/dp/B00ISNVQMW/ref=sr_1_5?nsdOptOutParam=true&s=shoes&sr=1-5",
      category: "Men",
      description: "Elegant watch for men.",
      price: 8000,
    },
    {
      id: 17,
      name: "Women's Watch",
      image: "https://www.amazon.in/NIBOSI-Watches-Analogue-Stylish-Diamond/dp/B0B2K2PLLD/ref=sxin_15_pa_sp_search_thematic_sspa?cv_ct_cx=Women%27s+Watch%5C&nsdOptOutParam=true&s=shoes&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sr=1-3-ced4eeeb-b190-41d6-902a-1ecb3fb8b7c4-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWM&psc=1",
      category: "Women",
      description: "Elegant watch for women.",
      price: 9000,
    },
    {
      id: 18,
      name: "Kids' Watch",
      image: "https://www.amazon.in/Acnos-Black-Rubber-Analogue-Watch/dp/B08DJ7BYBD/ref=sr_1_10?s=shoes&sr=1-10",
      category: "Kids",
      description: "Fun watch for kids.",
      price: 3000,
    },
    {
      id: 19,
      name: "Men's Sunglasses",
      image: "https://www.amazon.in/CREATURE-Protected-Black-Unisex-Sunglasses/dp/B09X6S5T9T/ref=sr_1_1_sspa?s=shoes&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
      category: "Men",
      description: "Stylish sunglasses for men.",
      price: 2000,
    },
    {
      id: 20,
      name: "Women's Sunglasses",
      image: "https://www.amazon.in/ENRICO-Protected-Poly-carbonate-Stuffy-Sunglasses/dp/B08FJHBHCG/ref=sr_1_13?s=shoes&sr=1-13",
      category: "Women",
      description: "Stylish sunglasses for women.",
      price: 2500,
    },
  ];
  
  export default products;