const products = [
  {
    id: 1,
    name: "Men's T-Shirt",
    image: "https://m.media-amazon.com/images/I/41ZM7fTZSWL._SX679_.jpg",
    description: "Comfortable cotton t-shirt for men.",
    price: 1200,
  },
  {
    id: 2,
    name: "Men's Jeans",
    image: "https://m.media-amazon.com/images/I/61lg3ufEX8L._SY879_.jpg",
    description: "Stylish denim jeans for men.",
    price: 2500,
  },
  {
    id: 3,
    name: "Men's Jacket",
    image: "https://m.media-amazon.com/images/I/61yp3ndG1JL._SY879_.jpg",
    description: "Warm and cozy jacket for men.",
    price: 3500,
  },
  {
    id: 4,
    name: "Men's Shoes",
    image: "https://m.media-amazon.com/images/I/71u78BeE5TL._SX695_.jpg",
    description: "Comfortable and stylish shoes for men.",
    price: 3000,
  },
  {
    id: 5,
    name: "Women's Dress",
    image: "https://m.media-amazon.com/images/I/61YN57FzrJL._SY879_.jpg",
    description: "Elegant dress for women.",
    price: 4000,
  },
  {
    id: 6,
    name: "Women's Handbag",
    image: "https://m.media-amazon.com/images/I/71nu6T+EUBL._SY695_.jpg",
    description: "Stylish handbag for women.",
    price: 2500,
  },
  {
    id: 7,
    name: "Women's Shoes",
    image: "https://m.media-amazon.com/images/I/61ijPj3VCLL._SY695_.jpg",
    description: "Comfortable and stylish shoes for women.",
    price: 3000,
  },
  {
    id: 8,
    name: "Women's Scarf",
    image: "https://m.media-amazon.com/images/I/813OBrN0KML._SX679_.jpg",
    description: "Beautiful scarf for women.",
    price: 1000,
  },
  {
    id: 9,
    name: "Kids' T-Shirt",
    image: "https://m.media-amazon.com/images/I/61J7UbM0xOL._SX679_.jpg",
    description: "Comfortable cotton t-shirt for kids.",
    price: 600,
  },
  {
    id: 10,
    name: "Kids' Jeans",
    image: "https://m.media-amazon.com/images/I/618xc8QXMYL._SY879_.jpg",
    description: "Stylish denim jeans for kids.",
    price: 1500,
  },
  {
    id: 11,
    name: "Kids' Jacket",
    image: "https://m.media-amazon.com/images/I/313JvUhdrXL.jpg",
    description: "Warm and cozy jacket for kids.",
    price: 2000,
  },
  {
    id: 12,
    name: "Kids' Shoes",
    image: "https://m.media-amazon.com/images/I/81uaP0tYJrL._SX695_.jpg",
    description: "Comfortable and stylish shoes for kids.",
    price: 1800,
  },
  {
    id: 13,
    name: "Men's Hat",
    image: "https://m.media-amazon.com/images/I/716u3DeaLfL._SX679_.jpg",
    description: "Stylish hat for men.",
    price: 800,
  },
  {
    id: 14,
    name: "Women's Hat",
    image: "https://m.media-amazon.com/images/I/41f4hxhH+OL.jpg",
    description: "Stylish hat for women.",
    price: 1000,
  },
  {
    id: 15,
    name: "Kid's Hat",
    image: "https://m.media-amazon.com/images/I/51C39DHMpTL.jpg",
    description: "Stylish hat for kids.",
    price: 600,
  },
  {
    id: 16,
    name: "Men's Watch",
    image: "https://m.media-amazon.com/images/I/61t5vb1LAUL._SX679_.jpg",
    description: "Elegant watch for men.",
    price: 8000,
  },
  {
    id: 17,
    name: "Women's Watch",
    image: "https://m.media-amazon.com/images/I/61uY-wl4OdL._SX679_.jpg",
    description: "Elegant watch for women.",
    price: 9000,
  },
  {
    id: 18,
    name: "Kids' Watch",
    image: "https://m.media-amazon.com/images/I/71QGGFAtOJL._SX679_.jpg",
    description: "Fun watch for kids.",
    price: 3000,
  },
  {
    id: 19,
    name: "Men's Sunglasses",
    image: "https://m.media-amazon.com/images/I/51wwVl2r-WL._SX679_.jpg",
    description: "Stylish sunglasses for men.",
    price: 2000,
  },
  {
    id: 20,
    name: "Women's Sunglasses",
    image: "https://m.media-amazon.com/images/I/41piJM2zJTL._SX679_.jpg",
    description: "Stylish sunglasses for women.",
    price: 2500,
  },
];

export default products;